### PR TITLE
Cleaning upmultipages

### PR DESCRIPTION
**Pull request by VVillTag**
Clean up the multiple pages
Move filters to sidebars
Placeholder for click through page
Function to change column names to proper case without underscore
Change style colouring to have live as green (Sorry Yassine)

### CODE REVIEW

**Comment by VVillTag** [comment]
Screenshot 2024-09-09 at 19 03 13
@yjebbaradaptavist  It looks like yes and hope its acceptable for you to merge

**Comment by yjebbaradaptavist** [comment]
@VVillTag It still doesn't make sense to me to add pages based on filtering that we can do on the first page. Thoughts @kd-adapt?

**Comment by VVillTag** [comment]
Happy to remove the other page for now @yjebbaradaptavist as we are still researching on clickthrough. I just hope this version will simplify and improve the user experience a little first. Maybe if you accept this version and then let me remove the other page in the next commit? 
The next page is essentially nothing at the moment: 
Screenshot 2024-09-09 at 19 16 03

**Comment by yjebbaradaptavist** [comment]
@VVillTag yeah ok fine no probs

**Comment by kd-adapt** [comment]
I agree it doesn't make sense to have a page just for bespoke services etc. longer-term
Do think it's useful to have a second page however (doesn't really matter what's in there), particularly given Emil's still in transit so hasn't been able to do anything yet, so there's a second page to link to for click-through testing

**Comment by VVillTag** [comment]
Cool thanks both. Going to merge this branch now to tidy things up a wee bit first then I will submit the table row select code that I just showcase on Slack
@yjebbaradaptavist  @kd-adapt

**Pull request merged**
